### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by rusgumeniuk** [rusgumeniuk/homepage#5]
Посилання на соцмережі (_Facebook чи Instagram, тощо_), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by RuslanHumeniuk** [comment]
### **DONALD TRUMP**

- https://www.fb.com/DonaldTrump
- realDonaldTrump@whitehouse.gov
- https://twitter.com/realDonaldTrump
- https://www.instagram.com/realDonaldTrump/
